Welcome to the PyTrieste wiki!

- [[The Unix Shell|Lesson1-TheUnixShell]]
- [[Version Control|Lesson2a-VersionControl]]
- [[Python 1: The Shell and Variables|Python1-ShellAndVariables]]
- [[Python 2: Lists, dictionaries, sets, and tuples|Python2-ListsDictsSetsTuples]]
- [[Python 3: Flow Control|Python3-FlowControl]]
- [[Python 4: Code Structure: Functions and Modules|Python4-FunctionsAndStandardModules]]
- [[Exercise Session 1 | ExerciseSession1-Basics]]
- [[Python 5: Strings and File I/O|Python-5:-Strings-and-File-I-O]]
- [[Python 6: Object oriented python|Python-6:-Object-oriented-programming]]
- [[Python 7: SciPy|Python7-SciPy]]
- [[Python 8: MatPlotLib|Python8-MatPlotLib]]
- [[Python 9: NumPy|Python9-NumPy]]
- [[Python 10: Testing|Python-10-Testing-your-program]]
