............................................
Python 5: Strings and File I/O
............................................

Lesson goals:

1) Examine the string class in greater detail.

2) Use open() to open, read, and write to files.

