all: roll-your-own motivation github

roll-your-own:
	nbconvert.py -f reveal roll_your_own_cms.ipynb

motivation: 
	nbconvert.py -f reveal 001-git-motivation.ipynb

github: 
	nbconvert.py -f reveal 004-github.ipynb
