#!/usr/bin/env python
import sys

import animals

if len(sys.argv) != 3:
    print 'Usage: meananimals filename species'
    sys.exit()

filename = sys.argv[1]
species = sys.argv[2]

sighted = animals.mean_animals_sighted(filename, species)
print sighted
